### PR TITLE
BDM on AWS 10.1.1 Update 2 

### PR DESCRIPTION
**Pull request by matanvr**
This is a pull request tracking upgrading BDM 10.1.0 to BDM 10.1.1 Update 2. All the changes corresponding to creating the BDM stack are now in one cloudformation script informatica-bdm-base.template. This refactoring allows us to modify one template for both quickstart/marketplace moving forward (Hence the new file). Both informatica-bdm-master and informatica-bdm call this template to create the BDM Stack. 

Most of the actual BDM upgrade changes were done in the AMI's, bootstrap.bash, and ebfinstall.sh. 

Note: The Tags in the script are internal to Informatica.

### CODE REVIEW

**Comment by santiagocardenas** [comment]
We should not be adding additional shim templates. This dilutes the value of the templates themselves. Can we combine both informatica-bdm.template and informatica-bdm-base.template into a single one?

**Comment by santiagocardenas** [comment]
Also, we are currently updating and simplifying the way we make calls to resources by eliminating the AWSInfoRegionMap and using Fn:Sub to build virtual-hosted S3 URLs. This can be seen in building blocks Quick Starts like VPC, Linux Bastion, and RD Gateway. This will need to be propagated going forward for other Quick Start updates.

**Comment by santiagocardenas** [comment]
Hi Matan, I can't diff this because the whole template was changed 2b82e94
Please revert those changes or do them separately and not as a commit.

From what I was able to see right away, the QS ID has been removed and the UserData is using -xe. We should not use those to ensure that we userdata doesn't exit and we can signal. Please keep the first line of UserData as "#!/bin/bash\n"

**Comment by matanvr** [comment]
Closing this pull request and creating a clean one.

**Pull request closed without merging**
